---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
      - WEBUI_PORT=8080
    volumes:
      - "D:/Media/.cache/Dockarr/qbittorrent/config:/config"
      - "D:/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    networks:
      - dockarr
    volumes:
      - "D:/Media/.cache/Dockarr/jackett/config/:/config"
      - "D:/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 9117:9117
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - dockarr
    volumes:
      - "D:/Media/.cache/Dockarr/radarr/config:/config"
      - "D:/Media/Movies:/movies"
      - "D:/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 7878:7878
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - dockarr
    volumes:
      - "D:/Media/.cache/Dockarr/sonarr/config:/config"
      - "D:/Media/TV Shows:/tv"
      - "D:/Media/Anime:/anime"
      - "D:/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 8989:8989
    restart: always
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - dockarr
    volumes:
      - D:/Media/.cache/Dockarr/bazarr:/config
      - D:/Media/Movies:/movies
      - D:/Media/TV Shows:/tv
      - "D:/Media/Anime:/anime"
    ports:
      - 6767:6767
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - dockarr
    volumes:
      - D:/Media/.cache/Dockarr/Jellyfin:/config
      - D:/Media/.cache/Dockarr/Jellyfin/cache:/cache
      - D:/Media:/media
    ports:
      - "8096:8096"
    restart: always
networks: 
    dockarr:
        driver: bridge