---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
      - WEBUI_PORT=8080
    volumes:
      - "/mnt/Media/Media/.cache/Dockarr/qbittorrent/config/:/config"
      - "/mnt/Media/Media/.cache/Dockarr/arr-downloads/:/downloads"
      - "/home/slenderboy/Media/Media/.cache/tor/Downloads/:/download-tor"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
    volumes:
      - "/mnt/Media/Media/.cache/Dockarr/radarr/config/:/config"
      - "/mnt/Media/Media/Movies:/movies"
      - "/mnt/Media/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 7878:7878
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
    volumes:
      - "/mnt/Media/Media/.cache/Dockarr/sonarr/config:/config"
      - "/mnt/Media/Media/TV Shows/:/tv"
      - "/mnt/Media/Media/Anime/:/anime"
      - "/mnt/Media/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 8989:8989
    restart: always
  
  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   hostname: bazarr
  #   networks:
  #     - dockarr
  #   volumes:
  #     - "/mnt/Media/Media/.cache/Dockarr/bazarr:/config"
  #     - "/mnt/Media/Media/Movies:/movies"
  #     - "/mnt/Media/Media/TV Shows/:/tv"
  #     - "/mnt/Media/Media/Anime/:/anime"
  #   ports:
  #     - 6767:6767
  #   restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
    volumes:
      - /mnt/Media/Media/.cache/Dockarr/Jellyfin/:/config
      - /mnt/Media/Media/.cache/Dockarr/Jellyfin/cache/:/cache
      - /mnt/Media/Media/:/media
    ports:
      - 8096:8096
    restart: 'always'
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - dockarr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=ASIA/KOLKATA
    ports:
      - "${PORT:-8191}:8191"
    restart: always
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - dockarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=ASIA/KOLKATA
    volumes:
      - /mnt/Media/Media/.cache/Dockarr/prowlarr/:/config
    restart: always
networks: 
    dockarr:
        driver: bridge