---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - dockarr
    environment:
      - TZ=ASIA/KOLKATA
      - WEBUI_PORT=8080
    volumes:
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/qbittorrent/config/:/config"
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    networks:
      - dockarr
    volumes:
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/jackett/config/:/config"
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 9117:9117
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - dockarr
    volumes:
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/radarr/config/:/config"
      - "/mnt/41C5368B25DE30D1/Media/Movies:/movies"
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 7878:7878
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - dockarr
    volumes:
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/sonarr/config:/config"
      - "/mnt/41C5368B25DE30D1/Media/TV Shows/:/tv"
      - "/mnt/41C5368B25DE30D1/Media/Anime/:/anime"
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/arr-downloads/:/downloads"
    ports:
      - 8989:8989
    restart: always
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - dockarr
    volumes:
      - "/mnt/41C5368B25DE30D1/Media/.cache/Dockarr/bazarr:/config"
      - "/mnt/41C5368B25DE30D1/Media/Movies:/movies"
      - "/mnt/41C5368B25DE30D1/Media/TV Shows/:/tv"
      - "/mnt/41C5368B25DE30D1/Media/Anime/:/anime"
    ports:
      - 6767:6767
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - dockarr
    volumes:
      - /mnt/41C5368B25DE30D1/Media/.cache/Dockarr/Jellyfin/:/config
      - /mnt/41C5368B25DE30D1/Media/.cache/Dockarr/Jellyfin/cache/:/cache
      - /mnt/41C5368B25DE30D1/Media/:/media
    ports:
      - 8096:8096
    restart: 'always'
networks: 
    dockarr:
        driver: bridge